export const menuCategories = [
  { id: "starters", name: "Starters", icon: "🥗" },
  { id: "burgers", name: "Burgers", icon: "🍔" },
  { id: "mains", name: "Main Course", icon: "🍖" },
  { id: "desserts", name: "Desserts", icon: "🍰" },
  { id: "beverages", name: "Beverages", icon: "🥤" },
];

export const menuItems = {
  starters: [
    {
      id: 1,
      name: "Crispy Buffalo Wings",
      description: "Golden fried wings tossed in our signature buffalo sauce",
      price: "$12.99",
      image: "/crispy-chicken-wings-golden-sauce-food-photography.jpg",
      isSpicy: true,
      isVeg: false,
      cookTime: "15 min",
      rating: 4.8,
    },
    {
      id: 2,
      name: "Truffle Loaded Fries",
      description: "Crispy fries topped with truffle oil and parmesan",
      price: "$9.99",
      image: "/truffle-loaded-fries-premium-food.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "10 min",
      rating: 4.6,
    },
    {
      id: 3,
      name: "Mozzarella Sticks",
      description: "Golden fried mozzarella with marinara sauce",
      price: "$8.99",
      image: "/mozzarella-sticks-golden.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "12 min",
      rating: 4.4,
    },
  ],
  burgers: [
    {
      id: 4,
      name: "The Classic Smash",
      description: "Double beef patty, caramelized onions, secret sauce",
      price: "$16.99",
      image: "/gourmet-smash-burger--melted-cheese--dark-moody-fo.jpg",
      isSpicy: false,
      isVeg: false,
      cookTime: "18 min",
      rating: 4.9,
    },
    {
      id: 5,
      name: "Nashville Hot Chicken",
      description: "Crispy fried chicken breast, Nashville hot seasoning",
      price: "$15.99",
      image: "/nashville-hot-chicken-burger-spicy.jpg",
      isSpicy: true,
      isVeg: false,
      cookTime: "20 min",
      rating: 4.7,
    },
    {
      id: 6,
      name: "Veggie Deluxe",
      description: "Plant-based patty with avocado and fresh veggies",
      price: "$14.99",
      image: "/veggie-burger-deluxe.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "16 min",
      rating: 4.5,
    },
  ],
  mains: [
    {
      id: 7,
      name: "BBQ Pulled Pork",
      description: "12-hour smoked pork shoulder with tangy BBQ sauce",
      price: "$18.99",
      image: "/bbq-pulled-pork-sandwich--coleslaw--brioche-bun--d.jpg",
      isSpicy: false,
      isVeg: false,
      cookTime: "25 min",
      rating: 4.8,
    },
    {
      id: 8,
      name: "Grilled Salmon",
      description: "Atlantic salmon with lemon herb butter",
      price: "$22.99",
      image: "/grilled-salmon-premium.jpg",
      isSpicy: false,
      isVeg: false,
      cookTime: "20 min",
      rating: 4.7,
    },
    {
      id: 9,
      name: "Chicken Alfredo",
      description: "Creamy alfredo pasta with grilled chicken",
      price: "$17.99",
      image: "/chicken-alfredo-pasta.jpg",
      isSpicy: false,
      isVeg: false,
      cookTime: "22 min",
      rating: 4.6,
    },
  ],
  desserts: [
    {
      id: 10,
      name: "Chocolate Lava Cake",
      description: "Warm chocolate cake with molten center",
      price: "$8.99",
      image: "/chocolate-lava-cake-dessert-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "12 min",
      rating: 4.9,
    },
    {
      id: 11,
      name: "Cheesecake Slice",
      description: "New York style cheesecake with berry compote",
      price: "$7.99",
      image: "/cheesecake-slice-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.8,
    },
  ],
  beverages: [
    {
      id: 12,
      name: "Craft Milkshake",
      description: "Thick vanilla milkshake with whipped cream",
      price: "$6.99",
      image: "/craft-milkshake-vanilla-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.5,
    },
    {
      id: 13,
      name: "Fresh Lemonade",
      description: "House-made lemonade with fresh mint",
      price: "$4.99",
      image: "/fresh-lemonade-mint.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "3 min",
      rating: 4.3,
    },
    {
      id: 14,
      name: "Craft Milkshake",
      description: "Thick vanilla milkshake with whipped cream",
      price: "$6.99",
      image: "/craft-milkshake-vanilla-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.5,
    },
    {
      id: 15,
      name: "Fresh Lemonade",
      description: "House-made lemonade with fresh mint",
      price: "$4.99",
      image: "/fresh-lemonade-mint.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "3 min",
      rating: 4.3,
    },
    {
      id: 16,
      name: "Craft Milkshake",
      description: "Thick vanilla milkshake with whipped cream",
      price: "$6.99",
      image: "/craft-milkshake-vanilla-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.5,
    },
    {
      id: 17,
      name: "Fresh Lemonade",
      description: "House-made lemonade with fresh mint",
      price: "$4.99",
      image: "/fresh-lemonade-mint.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "3 min",
      rating: 4.3,
    },
    {
      id: 18,
      name: "Craft Milkshake",
      description: "Thick vanilla milkshake with whipped cream",
      price: "$6.99",
      image: "/craft-milkshake-vanilla-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.5,
    },
    {
      id: 19,
      name: "Fresh Lemonade",
      description: "House-made lemonade with fresh mint",
      price: "$4.99",
      image: "/fresh-lemonade-mint.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "3 min",
      rating: 4.3,
    },
    {
      id: 20,
      name: "Craft Milkshake",
      description: "Thick vanilla milkshake with whipped cream",
      price: "$6.99",
      image: "/craft-milkshake-vanilla-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.5,
    },
    {
      id: 21,
      name: "Fresh Lemonade",
      description: "House-made lemonade with fresh mint",
      price: "$4.99",
      image: "/fresh-lemonade-mint.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "3 min",
      rating: 4.3,
    },
    {
      id: 22,
      name: "Craft Milkshake",
      description: "Thick vanilla milkshake with whipped cream",
      price: "$6.99",
      image: "/craft-milkshake-vanilla-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.5,
    },
    {
      id: 23,
      name: "Fresh Lemonade",
      description: "House-made lemonade with fresh mint",
      price: "$4.99",
      image: "/fresh-lemonade-mint.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "3 min",
      rating: 4.3,
    },
    {
      id: 24,
      name: "Craft Milkshake",
      description: "Thick vanilla milkshake with whipped cream",
      price: "$6.99",
      image: "/craft-milkshake-vanilla-premium.jpg",
      isSpicy: false,
      isVeg: true,
      cookTime: "5 min",
      rating: 4.5,
    },
    {
      id: 25,
      name: "Fresh Lemonade",
      description: "House-made lemonade with fresh mint House-made lemonade with fresh mint House-made lemonade with fresh mint",
      price: "$4.99",
      image: "/fresh-lemonade-mint.jpg",
      isSpicy: true,
      isVeg: true,
      cookTime: "3 min",
      rating: 4.3,
    },

  ],
};